name: List Merged PRs for Release

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  list-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List PRs and Prepare Slack Message
        id: list-prs
        run: |
          PR_NUMBERS=()
          
          declare -A SEEN_PR_NUMBERS
          declare -A PR_AUTHOR_BY_NUMBER
          declare -A PR_TITLE_BY_NUMBER
          declare -A PR_LINK_BY_NUMBER 
          declare -A PRS_BY_AUTHOR 

          # PRに含まれるコミットを取得
          COMMIT_OIDS=$(gh pr view ${{ github.event.pull_request.number }} --json commits --jq '.commits[].oid')

          # PRに含まれるコミットからPRのメタデータを取得
          for COMMIT_OID in $COMMIT_OIDS; do
            echo "Commit: $COMMIT_OID"

            PR_DETAILS=$(gh pr list --search "$COMMIT_OID" --state merged --json number,author,title --jq '.[0]')
            PR_NUMBER=$(echo "$PR_DETAILS" | jq -r '.number')

            if [[ -z "${SEEN_PR_NUMBERS[$PR_NUMBER]}" ]]; then
              PR_NUMBERS+=("$PR_NUMBER")
              SEEN_PR_NUMBERS["$PR_NUMBER"]=1

              PR_AUTHOR=$(echo "$PR_DETAILS" | jq -r '.author.login')
              PR_TITLE=$(echo "$PR_DETAILS" | jq -r '.title')
              PR_AUTHOR_BY_NUMBER["$PR_NUMBER"]="$PR_AUTHOR"
              PR_TITLE_BY_NUMBER["$PR_NUMBER"]="$PR_TITLE"
            fi
          done

          REPO_OWNER=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f1)
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)

          # PRリンクを作成し、authorごとにグループ化
          for PR_NUMBER in "${PR_NUMBERS[@]}"; do
            PR_LINK="https://github.com/$REPO_OWNER/$REPO_NAME/pull/$PR_NUMBER"
            PR_LINK_BY_NUMBER["$PR_NUMBER"]="$PR_LINK"

            PR_AUTHOR="${PR_AUTHOR_BY_NUMBER[$PR_NUMBER]}"
            PR_TITLE="${PR_TITLE_BY_NUMBER[$PR_NUMBER]}"

            # authorごとにPRをまとめる
            PRS_BY_AUTHOR["$PR_AUTHOR"]+="- <$PR_LINK|#$PR_NUMBER> $PR_TITLE\n "
          done

          SLACK_TEXT=""
          for AUTHOR in "${!PRS_BY_AUTHOR[@]}"; do
            SLACK_TEXT+=$(printf "%s\n%s\n" "$AUTHOR" "${PRS_BY_AUTHOR[$AUTHOR]}")
          done

          #   echo "$SLACK_JSON"
          # echo "pr_list=$(jq -R . <<< "$SLACK_TEXT")" >> "$GITHUB_OUTPUT"
          {
            echo "pr_list<<EOF"
            echo -e "$SLACK_TEXT"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send to Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: | 
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*リリース予定のPR一覧*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ steps.list-prs.outputs.pr_list }}
                  }
                }
              ]
            }
  